apiVersion: v1
kind: Namespace
metadata:
  name: targetns

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: targetsa
  namespace: targetns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: targetcr
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: targetcrb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: targetcr
subjects:
  - kind: ServiceAccount
    name: targetSA
    namespace: targetns

---
apiVersion: v1
kind: Service
metadata:
  name: targetsvc
  namespace: targetns
spec:
  selector:
    app: hello
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: targetdep
  namespace: targetns
spec:
  selector:
    matchLabels:
      app: hello
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
        tier: backend
        track: stable
    spec:
      containers:
        - name: hello
          image: 'gcr.io/google-samples/hello-go-gke:1.0'
          ports:
            - name: http
              containerPort: 80
---

