# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    N = 3 # max number of worker nodes
    Ver = '1.28.2' # Kubernetes Version to install
  
    #=============#
    # Master Node #
    #=============#
  
    config.vm.define "m-k8s" do |cfg|
      cfg.vm.box = "ubuntu/jammy64"  # Ubuntu 22.04 LTS (Jammy Jellyfish)
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "m-k8s-ubuntu"
        vb.cpus = 4
        vb.memory = 5120
        vb.customize ["modifyvm", :id, "--groups", "/k8s"]
      end
      cfg.vm.host_name = "m-k8s"
      cfg.vm.network "private_network", ip: "192.168.1.10"
      cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
      cfg.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt install -y zip bison build-essential cmake flex git libedit-dev \
            libllvm14 llvm-14-dev libclang-14-dev python3 zlib1g-dev libelf-dev libfl-dev python3-setuptools \
            liblzma-dev libdebuginfod-dev arping netperf iperf
        git clone https://github.com/iovisor/bcc.git
        mkdir bcc/build; cd bcc/build
        cmake ..
        make
        sudo make install
        cmake -DPYTHON_CMD=python3 .. # build python3 binding
        pushd src/python/
        make
        sudo make install
        popd
      SHELL
      cfg.vm.provision "shell", path: "config.sh", args: [N, 'Main']
      cfg.vm.provision "shell", path: "install_pkg.sh", args: [ Ver, "Main" ]
      cfg.vm.provision "shell", path: "master_node.sh"
    end
  
    #==============#
    # Worker Nodes #
    #==============#
  
    (1..N).each do |i|
      config.vm.define "w#{i}-k8s" do |cfg|
        cfg.vm.box = "ubuntu/jammy64"  # Ubuntu 22.04 LTS (Jammy Jellyfish)
        cfg.vm.provider "virtualbox" do |vb|
          vb.name = "w#{i}-ubuntu"
          vb.cpus = 2
          vb.memory = 5120
          vb.customize ["modifyvm", :id, "--groups", "/k8s"]
        end
        cfg.vm.host_name = "w#{i}-k8s"
        cfg.vm.network "private_network", ip: "192.168.1.10#{i}"
        cfg.vm.network "forwarded_port", guest: 22, host: "6010#{i}", auto_correct: true, id: "ssh"
        cfg.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update
            sudo apt install -y zip bison build-essential cmake flex git libedit-dev \
                libllvm14 llvm-14-dev libclang-14-dev python3 zlib1g-dev libelf-dev libfl-dev python3-setuptools \
                liblzma-dev libdebuginfod-dev arping netperf iperf
            git clone https://github.com/iovisor/bcc.git
            mkdir bcc/build; cd bcc/build
            cmake ..
            make
            sudo make install
            cmake -DPYTHON_CMD=python3 .. # build python3 binding
            pushd src/python/
            make
            sudo make install
            popd
        SHELL
        cfg.vm.synced_folder "../data", "/vagrant", disabled: true
        cfg.vm.provision "shell", path: "config.sh", args: [N, 'Worker']
        cfg.vm.provision "shell", path: "install_pkg.sh", args: Ver
        cfg.vm.provision "shell", path: "work_nodes.sh"
      end
    end
  end
  