# Layer2 configuration for MetalLB
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.11-192.168.1.19

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2config
  namespace: metallb-system
spec:
  ipAddressPools:
    - first-pool
